name: Cypress Cloud
on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress comand line 
        default: cypress/e2e/*
jobs:
  
  cypress-e2e-chrome:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.3.0
        with: 
          install-command: yarn install
          browser: chrome
          record: true
          group: UI Chrome 
          spec: ${{github.event.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: f111b73f-73a5-4c42-8244-dd484894fc8b
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-fire:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome103-ff107
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.3.0
        with: 
          install-command: yarn install
          browser: firefox
          record: true
          group: UI Firefox 
          spec: ${{github.event.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: f111b73f-73a5-4c42-8244-dd484894fc8b
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


 
 
