name: Cypress Cloud
on: 
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress comand line 
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0

      - name: Cypress run
        uses: cypress-io/github-action@v6.3.0
        with: 
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron 
          spec: ${{github.event.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: f111b73f-73a5-4c42-8244-dd484894fc8b
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
